# Generated by Django 4.1.7 on 2023-02-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_listing',
            new_name='Listing',
        ),
    ]
