# Generated by Django 4.1.7 on 2023-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
