# Generated by Django 4.1.7 on 2023-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_bid_is_closed_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_categories',
            field=models.CharField(choices=[('OT', 'Other'), ('CL', 'Clothing'), ('SH', 'Shoes'), ('AC', 'Accessories')], default='OT', max_length=2),
        ),
    ]
