# Generated by Django 4.1.7 on 2023-03-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on',
        ),
    ]
