# Generated by Django 4.1.7 on 2023-03-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_comment_unique_user_comment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_comment',
        ),
    ]
